services:
  api:
    build:
      context: .
      target: builder
    container_name: fastapi-application
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    develop:
      watch: 
        - action: sync
          path: ./app
          target: /app

        - action: sync
          path: requiremens.txt
          target: /app
